### ISSUE TITLE
Document enum values in GraphQL

### ISSUE THREAD

**Issue by HankC138** [goinvo/staffplan_redux#122]
Define and document:

- [x] Assignment#status
- [x] Client#status
- [x] Membership#status
- [x] Project#status

**Comment by fermion** [comment]
@HankC138 there's already a `status` that's intended to serve this purpose. Should we update the enum of allowed values for that field? For context, here's the enum list for [projects](https://github.com/goinvo/staffplan_redux/blob/1550f7bbf38623862d36f283f4d662e68830ccc3/app/models/project.rb#L23) and for [assignments](https://github.com/goinvo/staffplan_redux/blob/1550f7bbf38623862d36f283f4d662e68830ccc3/app/models/assignment.rb#L13).

**Comment by HankC138** [comment]
Ah I was under the impression it was a separate concept from the existing "status". I'll bring it up on the call tomorrow for clarification.

**Comment by fermion** [comment]
Okay, I'll leave this issue open, but only to create some enums in GraphQL for the various status fields that we have. I'll add the allowed values along with a description for each. That should cover it, 💭 @HankC138?

**Comment by HankC138** [comment]
> Okay, I'll leave this issue open, but only to create some enums in GraphQL for the various status fields that we have. I'll add the allowed values along with a description for each. That should cover it, 💭 @HankC138?

That should be perfect. 🚀
