### ISSUE TITLE
Visiting some pages signs you out from the app

### ISSUE THREAD

**Issue by fermion** [goinvo/staffplan_redux#154]
So far I see myself being signed out trying to add a new client avatar. Could be more. Need to investigate.

**Comment by fermion** [comment]
I can't seem to reproduce this. @HankC138 @jsonin you'd both observed this a few times, has this been occurring lately?

**Comment by HankC138** [comment]
I don't believe I ever encountered this issue myself. If I did I don't recall the cause.

**Comment by fermion** [comment]
Still an issue.
