### ISSUE TITLE
Need to base64 encode the current user's ID into the "My StaffPlan" URL

### ISSUE THREAD

**Issue by fermion** [goinvo/staffplan_redux#161]
The UI is expecting base64 encoded IDs in the URL. Change this URL to the correct route and encode the ID as a base64 value.

**Comment by HankC138** [comment]
I have changed this based on our conversation. Here is an example of what my own URI looks like. 

http://localhost:8080/people/%7B%22selectedUserId%22%3A%228%22%7D

![image](https://github.com/goinvo/staffplan_redux/assets/114195647/b31d8f02-ce3a-4ba7-89a2-4de88004d9ba)
here is the code snippet used to create the URI in the front end. If the backend could do this for the "myStaffPlan" link that would be great. Thank you.
