### ISSUE TITLE
Rate field to be added to project

### ISSUE THREAD

**Issue by HankC138** [goinvo/staffplan_redux#169]
based on a request from our last meeting, projects should have a field so we can save whether they are a "fixed" rate or "hourly" rate. I'm unsure what the best name for the field would be. "rateType"? Anything you think is more appropriate is fine with me.

**Comment by fermion** [comment]
Closed by https://github.com/goinvo/staffplan_redux/pull/172

**Comment by HankC138** [comment]
Oversight on my part. If we're saving fixed and hourly rateTypes we'll need to also save what that hourlyRate is IF a project is paid hourly. 🤦 I'm sorry I forgot to include that.
