### ISSUE TITLE
Add hourly rate optional field to projects

### ISSUE THREAD

**Issue by HankC138** [goinvo/staffplan_redux#174]
If a projects payRate is hourly we need a field to save that rate.

**Comment by fermion** [comment]
Integer or Decimal? IMO an integer should suffice, I've never seen hourly rates that go into cents. It's also safer to go from no precision to more precision (Integer => Decimal) with database types.

**Comment by fermion** [comment]
I'll make the default value here `0`

**Comment by fermion** [comment]
And also make it non-nullable, so we can assume a value is always there — it just might be 0.
