### ISSUE TITLE
Error received when trying to create a new account

### ISSUE THREAD

**Issue by dreeves4321** [goinvo/staffplan_redux#197]
I try to create an account. I receive the email and follow the link to confirm the account and receive an error screen.

![Image](https://github.com/goinvo/staffplan-next-app/assets/7915426/911261bf-7b93-4b49-93f7-fd629981b0ae)

**Comment by fermion** [comment]
Closing as this is an issue related to having a registration whose company name conflicts with an existing company. Going to open another issue for to capture the problem where we can discuss a solution.
