### ISSUE TITLE
Token email for login takes an age

### ISSUE THREAD

**Issue by jsonin** [goinvo/staffplan_redux#230]
What's an acceptable time-to-inbox from when I request a token/login credential?
5 sec? 10?

So far, I'm finding it to be 5 minutes+ on different 6 queries.

**Comment by fermion** [comment]
Depending on the issue there isn't going to be much that we can do about this, once the request is made to send emails out. We're currently on a free plan with capped number of daily sends and, if I had to guess, a lower priority for getting emails sent out.

I'd imagine that on a paid plan with any service that we'd see better turnaround time for email delivery. I'm going to get Amazon SES set up this week and we can try that out, see if that helps.

**Comment by fermion** [comment]
Switched to a production enabled SES, good to go 👍🏻
