### ISSUE TITLE
"StaffPlan" in browser tab: both in Redux and in UI

### ISSUE THREAD

**Issue by HankC138** [goinvo/staffplan_redux#299]
From an issue submitted by Juhan on the next-app I believe this is a backend issue:

 "Upon first login, to the stripe-page, the browser tab name is StaffPlanRedux.
How about just StaffPlan.

When on https://ui.staffplan.com/projects, it's "Staff Plan". No space.
Low priority.

for the total experience, it should all just be "staffplan.com" urls... we have ui.staffplan.com (which will confuse people who are not UI savvy).

Can we mask the url?"

**Comment by fermion** [comment]
@HankC138 I can update this for the Rails views, can you set this title for the React side?

**Comment by fermion** [comment]
@jsonin @HankC138 

> Can we mask the url?

What's this mean?

**Comment by HankC138** [comment]
> @HankC138 I can update this for the Rails views, can you set this title for the React side?

No problem at all space removed and will be fixed whenever my next PR goes thru

**Comment by fermion** [comment]
This should be all set.
