### ISSUE TITLE
Add an ability to accept array of workWeeks to the UpsertAssignment mutation. 

### ISSUE THREAD

**Issue by zhukovdigital** [goinvo/staffplan_redux#310]
For implementing functionality with fill forward button on UI for filling all presents weeks on the screen for assignment with current value in the input. 

https://github.com/goinvo/staffplan-next-app/issues/105

**Comment by fermion** [comment]
@zhukovdigital @HankC138 I'm thinking that introducing a new mutation, `upsertWorkWeeks` that takes an array work week data (`cweek`, `year`, `estimatedHours`, `actualHours`) for an `assignmentId` would work best here. Let me know if you disagree? I can get this in this week.

**Comment by zhukovdigital** [comment]
@fermion It`s ok for me, lets do it.

**Comment by fermion** [comment]
@zhukovdigital @HankC138 for the data that's returned, I was going to send back an Array of `WorkWeekType`s that were persisted to the database. Does that work? Alternatively I could send back the entire `AssignmentType`.

**Comment by zhukovdigital** [comment]
@fermion I think will be better send back entire AssignmentType with updated workweeks

**Comment by fermion** [comment]
Closed with https://github.com/goinvo/staffplan_redux/pull/315
