### ISSUE TITLE
Allow TBD user assignments to be deleted

### ISSUE THREAD

**Issue by HankC138** [goinvo/staffplan_redux#327]
Allow for assignments with no assigned user to be deleted

**Comment by fermion** [comment]
https://github.com/goinvo/staffplan_redux/commit/236a2e5d7bf61d1bb54fc05da5c1885560bf9f73

**Comment by jsonin** [comment]
Still not deleting... 
<img width="1487" alt="image" src="https://github.com/user-attachments/assets/31c4acbf-3d31-4cd3-9c8d-8bd4400c4bde">

**Comment by fermion** [comment]
@jsonin this added a backend mutation that will delete an assignment. The front end still needs to be updated to call this when someone's trying to remove a TBD assignment ❤️

**Comment by HankC138** [comment]
@jsonin I will be adding the front end implementation of this tomorrow morning it's already mostly done 🚀

**Comment by jsonin** [comment]
Ooops. Thx.
