### ISSUE TITLE
End of Week Email

### ISSUE THREAD

**Issue by jsonin** [goinvo/staffplan_redux#335]
Need an end of the week email to each planned person.
Sent 5p local time Friday (or???).
Goal = 1-click "yup, that looks right, those are my hours" and submit.

So the email should have a simple list of the projects you're currently planned on, that week's hour allocation, and something like, "Does this look like the hours you worked?"

**Yes** [auto-fill actuals from planned hours - no need to go to staffplan the service, but in email, have a feedback that says, "hours recorded"]
or
**No, make updates** and that leads to the staffplan service.

**Comment by fermion** [comment]
@jsonin what do you think about focusing less on email here in terms of complexity? Maybe an EOW reminder to check the current weeks' actual values? Or a beginning of week reminder to check the previous weeks' values? KISS. IMO we'll have more options at our disposal for cutting friction with a nice Slack/Teams integration.
