### ISSUE TITLE
Allow work weeks to be submitted with time even if assignedUser is null

### ISSUE THREAD

**Issue by HankC138** [goinvo/staffplan_redux#343]
As discussed in discord we need to be able to submit workWeeks for assignments that have no assignedUser

![image](https://github.com/user-attachments/assets/b719b44e-8a29-4a4d-a262-91005a0bf57c)

**Comment by fermion** [comment]
No PR for this one 😬 https://github.com/goinvo/staffplan_redux/commit/d130fdeb7391a9a09fade8401cd441b00ba6bd76
