### ISSUE TITLE
Add a `deleteProject` mutation

### ISSUE THREAD

**Issue by HankC138** [goinvo/staffplan_redux#381]
If a project has no assignments, or if the assignments have no assigned user or no actual hours, a project should allowed to be deleted. Similar to assignments a field of `canBeDeleted` would be helpful.

**Comment by HankC138** [comment]
@fermion could this one be created soon? We've had a couple requests for this functionality

**Comment by fermion** [comment]
Working on this now. I'm thinking that we could/should allow project deletion if there are assignees to a project's assignments. IMO the only thing that really should block a project from being deleted is if there have been hours recorded against it.

@jsonin @HankC138 @ericbenwa thoughts?

**Comment by fermion** [comment]
It opens the door to an accidental deletion, but I think the alternative (to unassign all assignees to a project's assignments, THEN delete the project) isn't a great UX. The UI should show a confirmation dialog before allowing project deletion if there are assignees to assignments, but not block it.

**Comment by fermion** [comment]
@HankC138 give the new mutation a shot. I also added the `Project#canBeDeleted` field that you'd asked for 👍🏻

**Comment by ericbenwa** [comment]
@fermion Yes, not great experience to delete all people from project before being able to delete the project.
We can baby step into deleting the project.

Today, it's ok if we only allow archiving a project.
And deleting people's assignments to a project if no actual hours against the project.

Future we can allow deleting the entire project, including the people's hours against it.
And agree, we should be clear it's destructive and get confirmation, or allow a simple undo.
This deleting of the entire project can be on the back-burner for now.
