### ISSUE TITLE
Stripe billing has a link back to the app

### ISSUE THREAD

**Issue by ericbenwa** [goinvo/staffplan_redux#408]
Once I add my payment method it feels like a dead end.
How do I get back to the StaffPlan app?
The app and Stripe is a little disjointed.

Does stripe allow some sort of link to bring me back to the app?
We might not be able to solve this right now, but checking what's possible here.

![stripe-billing](https://github.com/user-attachments/assets/b7084bdc-2ada-446f-a3cf-e4592a54272b)

**Comment by ericbenwa** [comment]
All set.
This links to the marketing website.

Tried linking to the app but got an error linking to the app itself, “Site can’t be reached”, staffplan.fermion.dev
<img width="982" alt="Image" src="https://github.com/user-attachments/assets/ef4eaadd-4fde-408b-b74d-c3ec7eea84af" />

**Comment by fermion** [comment]
Updated to point to app.staffplan.com.
