### ISSUE TITLE
Bug: Estimated/Actual Hours on work weeks are maxed at 24 hours

### ISSUE THREAD

**Issue by HankC138** [goinvo/staffplan_redux#96]
Estimated and Actual Hours on workWeek are limited to 24 hours max, this should be 40 for an entire week? Do we need to account for the potential of more than 40 weeks in the case of potential overtime?

**Comment by MyStarrySpace** [comment]
I think that having the option to add more than the current limit makes sense, especially for overtime. OTOH this brings up a good point; do we want to warn for overtime somehow?

**Comment by fermion** [comment]
@MyStarrySpace this is just my bad. When I was building this out initially I meant to put in a validation that the hours can't be more than there are hours in any one week. You can't possibly work 65,000 hours in a week, for example. I was going to bump this up 168 for the week, though that would be one hella week.
